Tuesday, 03/06/18 March 2018 17:07:12 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:11:23 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:15:03 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:17:14 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
Tuesday, 03/06/18 March 2018 17:17:26 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:17:55 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:18:53 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:22:03 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:25:52 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:30:24 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:31:25 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:32:23 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:33:54 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:35:54 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:37:56 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:39:53 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:40:07 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:41:23 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:43:02 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:43:16 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:45:04 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:47:34 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:50:56 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:51:10 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:52:56 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:56:55 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 17:59:55 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:06:56 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:10:36 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:12:23 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:12:29 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60748>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:12:34 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60D30>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:12:39 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DA9F97D748>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:12:44 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DA9F97D2B0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:12:50 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94160>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:12:55 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94128>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:13:01 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C944E0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:13:06 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94828>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:13:13 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94748>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:13:18 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C943C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:13:23 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C944A8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:13:28 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C947F0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:13:36 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C949E8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:13:41 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94D68>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:13:46 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94908>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:13:51 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94F60>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:14:01 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94C88>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:14:06 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2748>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:14:11 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2438>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:14:16 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94AC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:14:29 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C943C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:14:34 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94860>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:14:39 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94828>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:14:44 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C944E0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:15:00 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94F28>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:15:05 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94898>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:15:10 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DA9F97D860>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:15:15 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DA9F97D748>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:15:38 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C948D0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:15:43 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60BE0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:15:48 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60C18>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:15:53 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60F28>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:16:23 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60CF8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:16:28 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C784E0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:16:33 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C78588>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:16:38 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C78F60>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:17:22 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C78748>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:17:27 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2978>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:17:32 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2AC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:17:37 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA22E8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:18:12 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2470>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:18:17 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA28D0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:18:22 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2048>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:18:27 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2710>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:19:02 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C78A20>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:19:07 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C78BE0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:19:12 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60CF8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:19:17 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60940>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:19:52 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C609B0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:19:57 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60D30>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:20:02 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DA9F97D518>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:20:07 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DA9F97D7F0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:20:42 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60B70>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:20:47 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94198>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:20:52 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94668>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:20:57 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C944E0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:21:32 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C948D0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:21:37 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C942E8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:21:42 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C945C0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:21:47 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94AC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:22:22 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA23C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:22:27 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2CF8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:22:32 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2DA0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:22:37 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2E80>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:23:12 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2358>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:23:17 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CB4128>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:23:22 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CB41D0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:23:27 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CB42B0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:24:02 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94E10>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:24:07 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C943C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:24:12 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94588>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:24:17 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94B70>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:24:52 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94BA8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:24:57 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94128>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:25:02 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DA9F97D748>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:25:07 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DA9F97D5C0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:25:42 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94978>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:25:47 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C609B0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:25:52 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60BA8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:25:57 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60F28>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:26:32 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60DD8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:26:37 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C78240>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:26:42 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C787F0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:26:47 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CA2F28>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:27:22 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C78A90>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:27:27 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CB4470>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:27:32 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CB4518>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:27:37 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CB45F8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:28:12 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CB4320>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:28:17 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CB4908>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:28:22 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CB4A20>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:28:27 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CB4B38>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:29:02 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C787F0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:29:07 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C784E0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:29:12 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C78F60>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:29:17 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60D68>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:29:52 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C609B0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:29:57 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60D30>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:30:02 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60C18>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:30:07 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DA9F97D390>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:30:42 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C60BA8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:30:47 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94128>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:30:52 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94898>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:30:57 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94B70>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))
Tuesday, 03/06/18 March 2018 18:31:32 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C948D0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:31:37 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94400>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:31:42 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0C94860>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:33:08 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:35:16 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:35:22 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CC4320>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:35:27 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CC4828>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:35:32 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001DAA0CC4710>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot508830944:AAGdJMj2B8BSJ7tlV0oisa4ty2_9dMI386k/getUpdates
Tuesday, 03/06/18 March 2018 18:37:59 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:39:56 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:43:06 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:43:31 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:43:46 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:44:00 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:45:08 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:48:28 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:51:28 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:54:07 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:57:28 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 18:59:57 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 19:02:37 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 19:05:08 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 19:08:27 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 19:12:31 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 19:14:59 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 19:17:59 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 19:20:38 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
Tuesday, 03/06/18 March 2018 19:23:27 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
